### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by Fireworkstars46** [kui/7dtd-map#107]
What happened to the A20 and A21 options?

**Comment by kui** [comment]
I restored them.

These will be deleted at any time, so please fork them and host them on your own gh-pages if you need them in the future.

**Comment by Fireworkstars46** [comment]
What do you mean by fork them and deleted?

**Comment by kui** [comment]
See github documents:
* https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks
* https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages

**Comment by Fireworkstars46** [comment]
The A21 and A20 one works but for some reason I can't upload any files to it.

**Comment by kui** [comment]
Some files were not restored. Now fixed.

**Comment by Fireworkstars46** [comment]
Also would it be possible for me to use the map on a phone (iPhone specifically on iOS 18)?
