### ISSUE TITLE
dtm.raw not rendering 

### ISSUE THREAD

**Issue by Smugger21** [kui/7dtd-map#13]
DTM file is not rendering. Has something changed or is there a file size limit?

**Comment by Smugger21** [comment]
If it still works, I will re-write the upload and host it on one of my servers for large DTM files.

**Comment by kui** [comment]
DTM file is used for only "Elev" of the "Cursor" and the "Flag" displayed at the page left top.

I have no idea how to display the data.

**Comment by kui** [comment]
#2
