### ISSUE TITLE
Feature: use splat3_processed.tga instead of splat3.png

### ISSUE THREAD

**Issue by Laotseu** [kui/7dtd-map#17]
It would be nice if the renderer was able to use **splat3_processed.tga** or something else instead of **splat3.png** to render the roads. All the other files are available from the player side i.e. as a player I can use the renderer with the SaveLocal files to generate a map but it doesn't show the roads.

**Comment by kui** [comment]
7dtd-map now supports `splat3_processed.png` after 29a6e2fced49863d50726ba86ce82a3096cc11a4.

Thank you for your suggestion.
