### ISSUE TITLE
Add vending machine as block preset

### ISSUE THREAD

**Issue by dcsobral** [kui/7dtd-map#50]
It would also be particularly useful if the search could be limited to `cntVendingMachine2`, to find the always working ones.

**Comment by kui** [comment]
I have provided a button to find all types of vending machines.

`^cntVendingMachine.*(?&lt;!RandomLootHelper|Broken|Trader|Empty)$`
https://github.com/kui/7dtd-map/blob/7ac6ec94946b3efbbe9f35ba3b5dce3b9e6878b3/docs/index.html#L173-L175
