### ISSUE TITLE
Darkness Falls A20

### ISSUE THREAD

**Issue by Panerdar** [kui/7dtd-map#53]
Don't know if it is an issue with DF or your map preview. In past DF updates you could see all the city streets and prefabs. Now none of the city streets show for A20 Darkness Falls.

**Comment by SrslyGTFO** [comment]
Open the world in the world editor first (or start a game). That should generate the necessary files to render streets in the preview.

**Comment by kui** [comment]
I have no plans to support MOD content in this project. I will consider it if there is a Pull Request, but I myself have no plans to support additional content MODs.
