### ISSUE TITLE
Wrong mediatype detected for dtm.raw

### ISSUE THREAD

**Issue by ghandmann** [kui/7dtd-map#63]
Today i tried to render a generated map with your map renderer.

But i always get the following error:

```
Uncaught (in promise) Error: Unknown data type: name=dtm.raw, type=image/x-panasonic-rw
    at e.DtmHandler.handle (dtm-handler.ts:51:13)
    at index.ts:150:57
    at file-handler.ts:50:55
    at Array.map (<anonymous>)
    at e.FileHandler.processFiles (file-handler.ts:50:37)
    at async throttled-invoker.ts:9:11
```

After a quick look into [dtm-handler.ts:51](https://github.com/kui/7dtd-map/blob/master/src/index/dtm-handler.ts#L51) it looks like, that for some reason my browser detects the `dtm.raw` file with mime type `image/x-panasonic-rw`  which is not a valid option for the `dtm-handler`.

Tested this with Google Chrome 106.0.5249.61, Chromium 105.0.5195.125 and Opera 91.0.4516.20 (Chrome 105.0.0.0) always running on ubuntu 22.04.

**Comment by kui** [comment]
Thanks for the detailed report.

I found out that I was using it incorrectly and decided to use a simpler method instead!
