### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by Fireworkstars46** [kui/7dtd-map#87]
Do you have a discord server for it?

**Comment by Fireworkstars46** [comment]
Anyone active?

**Comment by kui** [comment]
There is no Discord server for this project. You can communicate through GitHub Issue and Pull Request. I am not good at English, so I avoid communication by chat and can only communicate in a certain amount of text.

**Comment by Fireworkstars46** [comment]
Would it be possible for me to use the map on a phone or is it only a pc thing to use?
